### ISSUE TITLE
Reuse zipkin armeria server to expose kafka-streams scatter-gather API  

### ISSUE THREAD

**Issue by jeqo** [openzipkin-contrib/zipkin-storage-kafka#40]
Following up #38 discussion to reuse zipkin-server via `consumer<ServerBuilder>`

**Comment by jeqo** [comment]
@anuraaga would love if you could give me some hints on how to solve this. I already have a `consumer<ServerBuilder>` available but I'm not sure how to proceed to integrate it with armeria server. 
Following the test-case here https://github.com/line/armeria/pull/2070/files#diff-d1e28023b060c9f088bd13bc0028d081R58-R60 seems to require spring dependency still or I might be missing something (not much experience with spring-boot here).

**Comment by anuraaga** [comment]
Have to remember our conversation - I believe our goal was to avoid the dependency on `armeria-spring` and `spring-boot`, not `spring`. While this module depends on boot since it provides properties and is conditional, I think you should be able to follow same pattern to provide `@Bean Consumer<ServerBuilder>`, which will get loaded by zipkin-server.
